# language: java
# jdk: oraclejdk8
env:
    matrix:
    - ANDROID_SDKS=android-10 ANDROID_TARGET=android-10 ANDROID_ABI=armeabi
    - ANDROID_SDKS=android-14 ANDROID_TARGET=android-14 ANDROID_ABI=armeabi_v7a
    - ANDROID_SDKS=sysimg-16 ANDROID_TARGET=android-16 ANDROID_ABI=armeabi_v7a
    - ANDROID_SDKS=sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi_v7a

language: android
android:
    components:
    - build-tools-19.0.2
    - $ANDROID_SDKS
    - $ANDROID_TARGET
    - $ANDROID_ABI
    licenses:
    - android-sdk-license-5be876d5
    
before_install:
    # Install base Android SDK
    # - sudo apt-get update -qq
    # - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    # - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
    # - tar xzf android-sdk_r23.0.2-linux.tgz
    # - export ANDROID_HOME=$PWD/android-sdk-linux
    # - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    
    # # Install required Android components
    # - android update sdk --filter platform-tools,android-16,extra-android-support,$ANDROID_SDKS --no-ui --force-yes
    
before_script:
    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    - chmod +x wait_on_emulator
    - ./wait_on_emulator
    
script: mvn install -Pintegration-tests -Dandroid.device=test